### ISSUE TITLE
Deployment testing: `HTTP error from reqwest`

### ISSUE THREAD

**Issue by nuke-web3** [risc0/risc0-foundry-template#104]
Following the deployment guide I can get to:
```
cargo run --bin publisher --     --chain-id=31337     --rpc-url="http://127.0.0.1:8545"     --contract=${EVEN_NUMBER_ADDRESS:?}     --input=12345678

...

Error: HTTP error from reqwest

Caused by:
    0: builder error: relative URL without a base
    1: relative URL without a base

```

Although the error isn't helpful... I did end up tracing to find the culprit:

https://github.com/risc0/risc0-foundry-template/blob/9658baac8d7e265aa22010d3310c72df3fc08619/apps/src/lib.rs#L84

Seems like there is a problem in https://github.com/risc0/risc0/blob/a6b884aa41dec6ae345013b7292e868d6e7685da/bonsai/sdk/src/alpha.rs#L421-L430 ?

Note: I have _not_ set BONSAI evn vars, but don't think that would lead to this error :crossed_fingers:

**Comment by IbrahimSam96** [comment]
It's talking about a url so this begs the question. Is it that --rpc-url="http://127.0.0.1:8545"  has `" "` unlike rest of vars? Wild guess!

**Comment by nategraf** [comment]
Closing this as fix because we removed the code that it relates to. Without an API key, it will now attempt to prove locally.
