### ISSUE TITLE
Unsupported protocol

### ISSUE THREAD

**Issue by 0xKarl98** [risc0/risc0-foundry-template#37]
The process is simple :
- run the setup command : 
`forge init -t risc0/bonsai-foundry-template ./your project `

- cargo build 

Then this message appears : 
error: failed to download from `https://crates.io/api/v1/crates/validator_derive/0.16.0/download`
Caused by:
  [1] Unsupported protocol (Received HTTP/0.9 when not allowed)

**Comment by pdg744** [comment]
Possibly related to this tip? 

<img width="680" alt="image" src="https://github.com/risc0/bonsai-foundry-template/assets/15272444/3d440ea8-a215-42d9-9211-9b842fc3bed9">

**Comment by 0xKarl98** [comment]
this doesn't help , i tried even though i doubt it :)

**Comment by nategraf** [comment]
Can you give some more information about the machine you are using? It seems very odd that your computer is using `HTTP/0.9`. Is it possible your system libraries are out of date?

**Comment by nategraf** [comment]
I'm going to close this issue as I don't believe its related to this repo. If you are still trying to get this to work, and you have some more details that will help us reproduce the issue, please let us know.
