### ISSUE TITLE
Dockerfile optimization

### ISSUE THREAD

**Issue by criadoperez** [risc0/risc0-foundry-template#49]
In the `Dockerfile` [line 8](https://github.com/risc0/bonsai-foundry-template/blob/main/Dockerfile#L8) we have:

``` 
COPY rust-toolchain.toml .
```

And then on [line 12](https://github.com/risc0/bonsai-foundry-template/blob/main/Dockerfile#L12):
```
COPY . . 
```

which copies the same file again. It would more efficient to simply make the `COPY . . ` first and not do the `COPY rust-toolchain.toml`.

**Comment by nategraf** [comment]
We decided to remove the Dockerfile from the repo. Thank you for opening this issue!
