### ISSUE TITLE
[Naming] Bonsai Foundry Template vs. RISC Zero Foundry Template

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0-foundry-template#84]
The new version of [Bonsai on Eth](https://dev.risczero.com/api/next/blockchain-integration/bonsai-on-eth) refers to the foundry template as the "RISC Zero Foundry Template." 

I'd like to be consistent in what we call things; are we changing the name of the Bonsai Foundry Template to the RISC Zero Foundry Template? This sounds like a good choice to me, but right now it feels like we're floating in between two names.

**Comment by nategraf** [comment]
After the rename, try running `forge init` and ensure that the redirect works with Forge
