### ISSUE TITLE
Refactor prover to use the risc0-zkvm API

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-foundry-template#92]
Currently the Foundry template includes code to call Bonsai with the Bonsai SDK. Proving with Bonsai is also provided under the unified API with `risc0-zkvm`, and this API is a much better user experience. We should refactor the template to use the `risc0-zkvm` API and drop the `BonsaiProver` type. This may require changes to the `risc0` monorepo.

Note that using the `risc0-zkvm` API does not immediately mean support for local proving. The blocker for local proving as an easily supported mode is the fact that the only prover option that works today is rapidsnark, and rapidsnark does not integrate nicely with our Rust workflows. As a result, we cannot yet provide a seemless local proving experience for Groth16, as some of the steps are manual and require Docker on x86 to run.

Resolved by: https://github.com/risc0/risc0-foundry-template/pull/106

**Comment by Cardosaum** [comment]
Waiting on [risc0 1689](https://github.com/risc0/risc0/issues/1689) before being able to move forward with this.

**Comment by Cardosaum** [comment]
Unblocked by [`risc0/` #1689](https://github.com/risc0/risc0/issues/1689) and [`risc0/` #1762](https://github.com/risc0/risc0/pull/1762).

**Comment by nategraf** [comment]
Related to `risc0-ethereum#110` but needs to be done here too

**Comment by capossele** [comment]
Fixed by #106
